### ISSUE TITLE
I am able to register multiple times via POST /api/users/register

### ISSUE THREAD

**Issue by mickeymond** [theophilusnuer/expense_tracker_app#6]
@theophilusnuer I think your user schema does not have the username and email set to unique thereby letting me register with the same username and password more than once.

**Comment by theophilusnuer** [comment]
@mickeymond I have worked on it and made the email and username unique. However, one can use same username but not the same email when registering. Hence, the frontend login is modified to accept email and password when logging in other than the username.
Thank you.
